### PR TITLE
Improved MiniMessage integration and more

### PR DESCRIPTION
**Pull request by 4drian3d**
- Updated Velocity version to 3.1.2, more than 1 year ago MiniMessage is now directly integrated into Velocity
- Added a correct permissions check and auto-completion to the /vmessage command
- Removed unused imports
- Removed some uses of legacy formatting in components

### CODE REVIEW

**Comment by FeuSalamander** [comment]
Thanks so much for your help and improving my plugin ! :)

**Comment by FeuSalamander** [comment]
If there are imports that are not used it causes problems ?

**Comment by 4drian3d** [comment]
> Just a question, If there are imports that are not used it causes problems ?

They don't cause any problems at runtime, they just... have no use, by removing them, you have a cleaner code and you optimize the memory usage of your IDE by not having to load extra classes

**Comment by FeuSalamander** [comment]
Ok Thanks

**Pull request merged**
